export enum ValidateProfileDataError {
  INCORRECT_USER_NAME = 'INCORRECT_USER_NAME',
  INCORRECT_USER_LASTNAME = 'INCORRECT_USER_LASTNAME',
  INCORRECT_AGE = 'INCORRECT_AGE',
  EMPTY_PROFILE_DATA = 'EMPTY_PROFILE_DATA',
  SERVER_ERROR = 'SERVER_ERROR',
}
