name: Check code quality

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up packages
        run: npm ci

      - name: Run lint TypeScript
        run: npm run lint:ts

      - name: Run lint CSS/SCSS
        run: npm run lint:scss

      - name: Run Unit testing
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run Screenshot testing
        run: npm run test:loki:ci

      - name: Build production
        run: npm run build:production